import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from numpy import *
from pandas import *

In [109]:
print(random.rand()) # 0~1 사이의 무작위 수
print(random.randn()) # -1 ~ 1 근처의 평균이 0이고, 표준편차가 1인 무작위 수

0.9505400649658974
-0.5583469708220996


-- Numpy
1. 숫자인 배열
2. 사칙연산
3. 1차원 ~ n차원
4. 리스트와 연결
5. 외부 라이브러리

In [110]:
list = [1, 5, 10, 15, 20, 25, 30]
print(list*3)
print(type(list))

[1, 5, 10, 15, 20, 25, 30, 1, 5, 10, 15, 20, 25, 30, 1, 5, 10, 15, 20, 25, 30]
<class 'list'>


In [111]:
arr = np.array(list)
print(list)
print(arr)

[1, 5, 10, 15, 20, 25, 30]
[ 1  5 10 15 20 25 30]


In [112]:
print(arr*3)
print(arr+3)
print(arr>=3)
print(type(arr))

[ 3 15 30 45 60 75 90]
[ 4  8 13 18 23 28 33]
[False  True  True  True  True  True  True]
<class 'numpy.ndarray'>


In [113]:
list2 = [[1,2,3], [4,5,6], [7,8,9],[10,11,12]]
print(type(list2))
print(len(list2))
print(list2*2)

<class 'list'>
4
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [114]:
arr2 = np.array(list2)
print(list2)
print(arr2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [115]:
print(len(arr2))
print(type(arr2))

4
<class 'numpy.ndarray'>


In [116]:
list3 = [[1.,2,3], [4,5,6], [7,8,9],[10,11,12]]
# 원소 1개만이라도 float이라면 모든 데이터는 float이 된다

In [117]:
arr3 = np.array(list3)
print(arr3)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [118]:
#List는 원소의 갯수를 Len(), 배열은 속성 size를 이용
print("배열의 크기:", arr.size)
print("배열의 크기:", arr2.size)
print("배열의 크기:", arr3.size)

배열의 크기: 7
배열의 크기: 12
배열의 크기: 12


In [119]:
print("데이터 타입의 바이트 수:", arr.itemsize)
print("데이터 타입의 바이트 수:", arr2.itemsize)
print("데이터 타입의 바이트 수:", arr3.itemsize)

print("배열의 전체 바이트 수:", arr.nbytes)
print("배열의 전체 바이트 수:", arr2.nbytes)
print("배열의 전체 바이트 수:", arr3.nbytes)

print("배열의 원소의 데이터 형:", arr.dtype)
print("배열의 원소의 데이터 형:", arr2.dtype)
print("배열의 원소의 데이터 형:", arr3.dtype)

print("배열의 차원:", arr.ndim)
print("배열의 차원:", arr2.ndim)
print("배열의 차원:", arr3.ndim)

print("배열의 행렬 크기:", arr.shape)
print("배열의 행렬 크기:", arr2.shape)
print("배열의 행렬 크기:", arr3.shape)

데이터 타입의 바이트 수: 8
데이터 타입의 바이트 수: 8
데이터 타입의 바이트 수: 8
배열의 전체 바이트 수: 56
배열의 전체 바이트 수: 96
배열의 전체 바이트 수: 96
배열의 원소의 데이터 형: int64
배열의 원소의 데이터 형: int64
배열의 원소의 데이터 형: float64
배열의 차원: 1
배열의 차원: 2
배열의 차원: 2
배열의 행렬 크기: (7,)
배열의 행렬 크기: (4, 3)
배열의 행렬 크기: (4, 3)


In [120]:
print(arr)
print("전치행렬 \n", arr.T)

print("\n",arr2)
print("전치행렬 \n", arr2.T)

[ 1  5 10 15 20 25 30]
전치행렬 
 [ 1  5 10 15 20 25 30]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
전치행렬 
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [121]:
arr2[0], arr2[-1]

(array([1, 2, 3]), array([10, 11, 12]))

In [122]:
arr[0:3]

array([ 1,  5, 10])

In [123]:
arr2[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
arr2[:, 1:3] #1열과 2열만

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [125]:
arr2[:, :2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [126]:
arr2[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [127]:
arr2[0:4, 0:2], arr2[:, :2]

(array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]))

In [128]:
np.zeros(4) # float 형의 0을 가지는 배열 생성

array([0., 0., 0., 0.])

In [129]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [130]:
np.ones(4) # float 형의 1을 가지는 배열 생성

array([1., 1., 1., 1.])

In [131]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [132]:
np.full(4, 5.2)

array([5.2, 5.2, 5.2, 5.2])

In [133]:
np.full((2,3), 6)

array([[6, 6, 6],
       [6, 6, 6]])

In [134]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [135]:
a = np.eye(3)
b = np.array([[1,2,3],[1,2,3],[1,2,3]])

print(a+b)
print(a*b) # 이는 배열의 원소들의 단순한 곱

[[2. 2. 3.]
 [1. 3. 3.]
 [1. 2. 4.]]
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [136]:
np.dot(a, b) # 배열의 곱 -> a배열이 항등 배열로써 곱셈 후 b값이 그대로 출력

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [137]:
a = range(5)
print(type(a))
print(a)

<class 'range'>
range(0, 5)


In [138]:
b = np.arange(5)
print(type(b))
b

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

In [139]:
c = np.arange(6)
print(type(c))
c

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5])

In [140]:
c.shape = (2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [141]:
e = c.flatten()
e

array([0, 1, 2, 3, 4, 5])

In [142]:
e.resize(3,2)
e

array([[0, 1],
       [2, 3],
       [4, 5]])

In [143]:
e = e.astype(np.float64)
e

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [144]:
data = np.arange(12).reshape(4,3)
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [145]:
data2 = np.arange(0, 12, 1).reshape(4,3)
data2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [146]:
data3 = np.arange(0, 24, 2).reshape(4,3)
data3

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [147]:
data3 >= 10

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [148]:
data3[data3 >= 10] = 3
data3

array([[0, 2, 4],
       [6, 8, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [149]:
data3.max()

np.int64(8)

In [150]:
data3.max(axis=1)

array([4, 8, 3, 3])

In [151]:
data3.max(axis=0)

array([6, 8, 4])

In [152]:
print(data3.sum())
print(data3.sum(axis=1))
print(data.sum(axis=0))

41
[ 6 17  9  9]
[18 22 26]


In [153]:
data4 = np.random.randint(1, 50, (4,5))
data4

array([[12, 12, 35,  6, 37],
       [46, 38, 47, 36, 11],
       [46, 12, 21,  8, 28],
       [38, 14, 35, 25, 35]], dtype=int32)

In [154]:
data4.sort() #기본적으로 행단위로 오름차순 정렬
data4

array([[ 6, 12, 12, 35, 37],
       [11, 36, 38, 46, 47],
       [ 8, 12, 21, 28, 46],
       [14, 25, 35, 35, 38]], dtype=int32)

In [155]:
data4.sort(axis=0) # 열 단위 정렬
data4

array([[ 6, 12, 12, 28, 37],
       [ 8, 12, 21, 35, 38],
       [11, 25, 35, 35, 46],
       [14, 36, 38, 46, 47]], dtype=int32)

In [156]:
data4.sort(axis=1) # 행 단위 정렬
data4

array([[ 6, 12, 12, 28, 37],
       [ 8, 12, 21, 35, 38],
       [11, 25, 35, 35, 46],
       [14, 36, 38, 46, 47]], dtype=int32)

In [157]:
data4 = np.sort(data4)[::-1] # np.sort는 기본으로 열단위 정렬
data4

array([[14, 36, 38, 46, 47],
       [11, 25, 35, 35, 46],
       [ 8, 12, 21, 35, 38],
       [ 6, 12, 12, 28, 37]], dtype=int32)

In [158]:
data4 = np.sort(data4, axis=1)[::-1]
data4

array([[ 6, 12, 12, 28, 37],
       [ 8, 12, 21, 35, 38],
       [11, 25, 35, 35, 46],
       [14, 36, 38, 46, 47]], dtype=int32)

In [159]:
data4 = np.sort(data4, axis=0)[::-1]
data4

array([[14, 36, 38, 46, 47],
       [11, 25, 35, 35, 46],
       [ 8, 12, 21, 35, 38],
       [ 6, 12, 12, 28, 37]], dtype=int32)

In [160]:
np.linspace(0,100,9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [161]:
np.logspace(0,100,10)

array([1.00000000e+000, 1.29154967e+011, 1.66810054e+022, 2.15443469e+033,
       2.78255940e+044, 3.59381366e+055, 4.64158883e+066, 5.99484250e+077,
       7.74263683e+088, 1.00000000e+100])